// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAruaAr5_v9ZpC-Ei9mn6rFuAsBPlSUDY4',
    appId: '1:144559493260:web:fdc133430299b83e42aba9',
    messagingSenderId: '144559493260',
    projectId: 'chatapp-8fd30',
    authDomain: 'chatapp-8fd30.firebaseapp.com',
    databaseURL: 'https://chatapp-8fd30-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8fd30.appspot.com',
    measurementId: 'G-E3N695J35Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRI8dxIgAtEGR5_XwJyjbWl98IdIO-zqk',
    appId: '1:144559493260:android:36c4ebb6e753993b42aba9',
    messagingSenderId: '144559493260',
    projectId: 'chatapp-8fd30',
    databaseURL: 'https://chatapp-8fd30-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8fd30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6gDvM2KHSSacNI3lAntLr4FdEfRQNkhY',
    appId: '1:144559493260:ios:d4fe5e0364ac3bba42aba9',
    messagingSenderId: '144559493260',
    projectId: 'chatapp-8fd30',
    databaseURL: 'https://chatapp-8fd30-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8fd30.appspot.com',
    iosBundleId: 'com.example.workInstaMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6gDvM2KHSSacNI3lAntLr4FdEfRQNkhY',
    appId: '1:144559493260:ios:d4fe5e0364ac3bba42aba9',
    messagingSenderId: '144559493260',
    projectId: 'chatapp-8fd30',
    databaseURL: 'https://chatapp-8fd30-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8fd30.appspot.com',
    iosBundleId: 'com.example.workInstaMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAruaAr5_v9ZpC-Ei9mn6rFuAsBPlSUDY4',
    appId: '1:144559493260:web:958b4f9b3150a98042aba9',
    messagingSenderId: '144559493260',
    projectId: 'chatapp-8fd30',
    authDomain: 'chatapp-8fd30.firebaseapp.com',
    databaseURL: 'https://chatapp-8fd30-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8fd30.appspot.com',
    measurementId: 'G-RK6LTZXN84',
  );
}
